### ISSUE TITLE
HMMER 3.1b2

### ISSUE THREAD

**Issue by VadimDu** [rdpstaff/Xander_assembler#5]
Dear developer,

I am planning to use Xander for assembling antibiotic resistance genes from metagenomes.
I am using HMMER version 3.1b2. Do I need to use the hmmer-3.0_xanderpatch for creating specialized forward and reverse HMMs? 
If yes, will this patch will work with my version or do you have a newer patch?
if no, then which commands/options do I need to change in prepare_gene_ref.sh?

Glad for your assistance
Best regards
Vadim

**Comment by gunturus** [comment]
No. you will need the patch if you are using hmmer 3.0

**Comment by VadimDu** [comment]
Thank you!
