### ISSUE TITLE
Is Xander accepting paired end reads?

### ISSUE THREAD

**Issue by VadimDu** [rdpstaff/Xander_assembler#6]
Dear developer,
I could not find in any place in the article/documentation if Xander works with paired-end reads? Do they need to be interlaced in a single file with consecutive lines? Or they need to be in separated files reverse-forward?
In the Xander paper the authors used merged reads, but if the insert size is > then read length x 2 as is usually the case in Illumina reads how to proceed?.
I would greatly appreciate if you can clarify on this.

Best Regards
Vadim Dubinsky

**Comment by gunturus** [comment]
You will need to merge the reads. If you can't, we only accept foward reads
